import { createGlobalState } from "react-hooks-global-state";

const { setGlobalState, useGlobalState } = createGlobalState({
    thumbtake: 10,
    thumbskip: 0,
    relatedtake: 10,
    relatedskip: 0,
    editingMode: false,
    urlData: 0,
    managementUrlData: "",
    managementUrlDataName:"",
    managementUrlDataProductType:"",
    managementUrlDataProductBrand:"",
    managementUrlDataCategory:"",
    rowNumber: 0,
    setInitSlice: 1,
    fromDate: null,
    toDate: null,
    ItemPerpage: 10,
    CurrentPage:1,
    NewsItemPerpage: 5,
    NewsSetInitSlice:1,
    setReciever:"",
    useDrawer:"-100",
    messageCount:[],
    AgentPerpage: "Select Email Address",
    // setInitSlice:"0",
    setNewsData:"",
    setPrivacyData:"",
    setDisclaimerData:"",
    setAbout:"",
    setItemID: "",
    message: "",
    useEmail: "",
    useLevel: "",
    Management: [],
    cookieEmailAddress: "",
    cookieUserLevel: "",
    cookieActiveUser: "",
    productSearch: "",
    thumbnailData: null,
    productCategory: "Select Category",
    productType: "Select Product Type",
    productBrand: "Select Product Brand",
    descAsc: null,
    activeModel: "http://localhost:3000/models/NoModel.glb",
    CurrentDrawer:true,
    categoryFilter:"Select Category",
    productTypeFilter:"Select Product Types",
    accountFormDataEdit:{
        accountLevel: '',
        Address: '',
        accountEmail: '',
        contactNo: '',
        fullname: '',
        loginAttemp: '',
        macAddress: '',
        agentIdentity: '',
        nameOfStore: '',
    },
    invFormDataEdit:{
        Id:'',
        Name:'',
        Category:'Select Category',
        ProductType:'Select Product Type',
        Brandname:'Select Product Brand',
        Status:'Select Status'
    },
    invFormDataAdd:{
        Name:'',
        Category:'Select Category',
        ProductType:'Select Product Type',
        Brandname:'Select Product Brand',
        Status:'Select Status',
    },
    invFormDetailDataAdd:{
        Color:"",
        Size:"",
        Price:"",
        Stock:"",
        Description:""
    },
    invFormDetailDataEdit:{
        productCode:"",
        styleCode:"",
        Color:"",
        Size:"",
        Price:"",
        Status:"Active",
        Stock:"",
        Description:"",
        Id:""
    },
    newsForm:{
        Title:"",
        Image:"",
        Summary:""
    }
});
export { useGlobalState, setGlobalState };
